language: python
script: python -m py_compile PyProCI/src/pyspark.py
install: 
    - pip install pyspark
after_success: 
    - curl -i -X PUT "http://172.17.0.2:50070/webhdfs/v1/data/a.txt?op=CREATE&user.name=hdfs"
    - curl -i -X PUT "http://172.17.0.2:50075/webhdfs/v1/data/a.txt?op=CREATE&user.name=hdfs&namenoderpcaddress=sandbox.hortonworks.com:8020&createflag=&createparent=true&overwrite=false"



